In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.utils.validation import check_is_fitted

In [2]:
# Define the wrangle function
def wrangle(filepath):
    # Import CSV
    df = pd.read_csv(filepath)
    
    # Remove outlier
    low, high = df["median_house_value"].quantile([0.1, 0.9])
    mask = df["median_house_value"].between(low, high)
    
    df = df[mask]
    
    return df

In [3]:
#Import data using the define wrangle function
df = wrangle("California_housing.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY,342200
5,-122.25,37.85,52,919,213.0,413,193,4.0368,NEAR BAY,269700
...,...,...,...,...,...,...,...,...,...,...
20633,-121.53,39.19,27,2080,412.0,1082,382,2.5495,INLAND,98300
20634,-121.56,39.27,28,2332,395.0,1041,344,3.7125,INLAND,116800
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND,92300
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND,84700
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND,89400